version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DATABASE: myDB
  REACT_APP_SERVER_PORT: 4001

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8889:8889
    restart: unless-stopped
    volumes:
      - ./db/myDB.sql:/docker-entrypoint-initdb.d/myDB.sql
  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 4001
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 4001:4001
    volumes:
      - ./server:/app
    links:
      - mysql
    command: yarn start
  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: yarn start
